import = [
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/katsushika.toml"
  "~/.config/alacritty/kanagawa_wave.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"
